dir_cases = []
dir_cases.append(r"\bnorth\b")
dir_cases.append(r"\bn\b")
dir_cases.append(r"\bsouth\b")
dir_cases.append(r"\bs\b")
dir_cases.append(r"\be\b")
dir_cases.append(r"\beast\b")
dir_cases.append(r"\bw\b")
dir_cases.append(r"\bwest\b")
dir_cases.append(r"\bnorthwest\b")
dir_cases.append(r"\bnw\b")
dir_cases.append(r"\bsouthwest\b")
dir_cases.append(r"\bsw\b")
dir_cases.append(r"\bnortheast\b")
dir_cases.append(r"\bne\b")
dir_cases.append(r"\bsoutheast\b")
dir_cases.append(r"\bse\b")           